package de.fwinkel.android_stunnel;

import java.util.ArrayList;
import java.util.List;

import androidx.annotation.NonNull;

/**
 * Manages a list of config lines (mostly key-value, see {@link StunnelOption}).<br/>
 * @param <T> Must be the implementing class or one of its ancestors.
 */
abstract class StunnelConfigBuilder<T extends StunnelConfigBuilder> {

    protected final List<String> config = new ArrayList<>();

    /**
     * Adds a raw config string such as generated by {@link StunnelOption#toConfigString()} to {@link #config}.
     * @param configOption
     * @return
     */
    protected T addConfig(@NonNull String configOption) {
        config.add(configOption);
        return (T) this;
    }

    /**
     * Adds a raw key/value config setting. Usually you should prefer the various high-level setters.
     * @param name
     * @param value
     * @return
     */
    public T setOption(@NonNull String name, @NonNull String value) {
        return setOption(new StunnelOption<>(name, value));
    }

    /**
     * Adds a raw key/value config setting. Usually you should prefer the various high-level setters.
     * @param option
     * @return
     */
    public T setOption(@NonNull StunnelOption option) {
        return addConfig(option.toConfigString());
    }
}
